### ISSUE TITLE
Publish to the PowerShellGallery

### ISSUE THREAD

**Issue by dotps1** [JanDeDobbeleer/oh-my-posh2#11]
Can you publish this to the PowerShellGallery.  I don't have PsGet and the cmdlets from it interfere with the built in PackageManagment module.

thanks.

**Comment by JanDeDobbeleer** [comment]
I'll see what I can do!

**Comment by dotps1** [comment]
yeah, it would be nice, I installed PsGet just to get this running, and it totally borks the default PackageMgmt module, guessing because it installs in the Users Module dir, which PS looks in first.

thanks.

**Comment by JanDeDobbeleer** [comment]
Ok, I looked into this and it's not really an option. Some of the modules are not available in the gallery:
- Invoke-ElevatedCommand
- out-diff
- PoShAncestry
- PoShWarp
- PsUrl

So, the default package management gets confused because PsGet installed a few modules in the user module dir? Sounds like the default package manager has an issue iso PsGet.

**Comment by Liquidmantis** [comment]
@dotps1 I'm avoiding PsGet for the same reason.  There are comments in issues on the PsGet project that acknowledge it is mostly obsolete with WM5.  Personally, I just cloned the oh-my-posh repo into my user scope Powershell module directory, did not run the installer, and haven't worried about the other modules.  I'm not sure how they're used by oh-my-posh but I haven't yet had any issues without them.  
It's my **personal** opinion that the best path forward would be for all community modules to migrate to the official Powershell Gallery, especially since WMF5 is available for all still-relevant downlevel operating systems, not just Windows 10.

**Comment by JanDeDobbeleer** [comment]
The other modules aren't used apart from posh-git. I could remove them and still publish this to the gallery though if that would make it future-proof. But in all honesty the guides on how to properly package and publish are rubbish. Do you guys know of a straightforward one?

**Comment by Liquidmantis** [comment]
I've only pulled from the Powershell Gallery.  I do run an internal ProGet repo at work though and it's straightforward to publish a module to it.  PSGallery should be the same other than getting a Nuget API key.  Let me see what I can turn up.

**Comment by Liquidmantis** [comment]
Yeah, it looks exactly the same with Powershell gallery except easier.  With WMF5 and the included PowershellGet module (was OneGet) it's registered as the default repository so you don't even have to add it.  All you need to do is sign up at https://www.powershellgallery.com/ to get an account then go to your profile to get the API key that it generates for you. With that use
`Publish-Module -Name <moduleName> -NuGetApiKey <apiKey>`
from inside the module directory or use -Path to specify the directory.   You will need WMF5 installed though.

[Edit] I recommend using -Verbose so you get some useful feedback on what's happening.

**Comment by JanDeDobbeleer** [comment]
Let me give that a go asap.

**Comment by JanDeDobbeleer** [comment]
It's live, I tested it. Works like a charm.

https://www.powershellgallery.com/packages/oh-my-posh/1.3

**Comment by Liquidmantis** [comment]
Yup!  Looks good on my cleanslate VM, other than the errors from my VM missing git and Powerline font prereqs.  Thanks for releasing it on PS Gallery!

![image](https://cloud.githubusercontent.com/assets/399056/17262029/46e4fb50-5596-11e6-9b54-0ca54dd7f933.png)

**Comment by JanDeDobbeleer** [comment]
I'm going to automate the publishing using AppVeyor so it's always up to date. I'll close this once the branch is merged to master.

**Comment by dotps1** [comment]
Thanks for this, I just _re-installed_ using the gallery, but I have to be honest, if those other _10-ish_ modules where not used, then why where they included? and now, my prompt loads way faster when there is only 2 modules that import rather then 10.

**Comment by JanDeDobbeleer** [comment]
I added them because I use them and love em. I narrowed it down to only 3 now but I might remove it altogether. I wasn't sure which road to take, but for the sake of simpleness, I'll remove them.

**Comment by Liquidmantis** [comment]
Thanks!  At risk of being annoying by throwing out my opinion again, it would seem a better practice would be just importing those modules in your profile if they aren't requirements for oh-my-posh.  You might mention them in the readme as recommended additions with quick explanations of how you incorporate them in your workflow.

**Comment by JanDeDobbeleer** [comment]
That was my plan 😉

**Comment by JanDeDobbeleer** [comment]
Everything is merged and fully operational :+1:
