### ISSUE TITLE
oh-my-posh exports a lot of very generally named functions

### ISSUE THREAD

**Issue by cyanite** [JanDeDobbeleer/oh-my-posh2#216]
This easily collides with other functions. When those exported are less capable, then, it becomes a problem. One such as Get-FullPath which *only* accepts a PathInfo, so it can't be called with strings. This breaks our profile where we export one that accepts a string (which *also* works with PathInfo).

But in general, many of the exported functions have far too general names, IMO, and are likely to collide with other modules. For functions only used externally, like Get-FullPath, is it really necessary to export them?

**Comment by JanDeDobbeleer** [comment]
Yes as you can't make a custom theme without them (well you could, but you'd be reinventing the wheel often enough to justify exporting them). This is the first time I hear collision issues in 2 years, I could be open to suggestions for renames but I have no info on how many custom themes that might break.

**Comment by cyanite** [comment]
You gotta admit, though, it's a *very* general name, one that might as well have come from PowerShell itself.

And it does work a bit strange. For example, Get-FullPath C:\ returns C:, but this is dangerous (and incorrect), since C: in Windows generally means "read the hidden env variable to determine the 
current dir of C:". The following sequence illustrates that error:

    X:
    $d = Get-FullPath (pwd)
    cd test
    C:
    'ohnoes' > (Join-Path $full 'test.txt')

which will result in the file being written as X:\test\test.txt, which seems incorrect.

This command really should be called Get-PoshFullPath or at least Get-PromptFullPath, since it's so specific to posh.

**Comment by Liquidmantis** [comment]
Test-Administrator is one that conflicts with an internal module at my office.  While all of my PS modules are written for internal uses, I namespace all of my functions (Test-Administrator isn't mine, but is also a generic function) with a common module prefix so that they don't get clobbered by a public module.  For example, Get-OmpFullPath would be a naming pattern matching my norm.

**Comment by dudeofawesome** [comment]
`Get-Theme` also overlaps with Pansies' `Get-Theme`

**Comment by cyanite** [comment]
In general, all such commands should be named something like Verb-PoshNoun (or Omp), since it's the only way to be sure.

This pretty much demonstrates the weakness of PowerShell's Verb-Noun scheme.

**Comment by jfishe** [comment]
I changed my profile to:

``` powershell
Import-Module posh-git
Import-Module oh-my-posh -Prefix 'OMP'
Set-OMPTheme Agnoster
```
That appears to work fine for $prompt, but I noticed that completion with Set-OMPTheme no longer works.

**Comment by sql-sith** [comment]
If we do add a prefix, I think we should use something like `omp` or `omposh` instead of just `posh`, since the `posh-git` module, in my opinion, should have prior claim to the `posh` prefix. It could also confuse people if they look at their variable (instead of reading the docs) when trying to tweak their prompts. Just my 0.02.

**Comment by JanDeDobbeleer** [comment]
This is feature of V3 https://ohmyposh.dev
