### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by FlorentLM** [JanDeDobbeleer/oh-my-posh2#236]
Hi,

I just tried disabling the window title option with  `$ThemeSettings.Options.ConsoleTitle = $false`  and it indeed seems to allow me change the value (it is set to False when I try `$ThemeSettings.Options` ) but the window title won't change, and if I try `$ThemeSettings.Options` again in a new tab / new window, the setting is reverted.

I tried changing the default value (in `C:\Users\me\Documents\PowerShell\Modules\oh-my-posh\2.0.342\defaults.ps1` ) and that dd the trick. What am I doing wrong?

Thanks

**Comment by sassdawe** [comment]
Hey @FlorentLM,

Updating the `defaults.ps1` is one way to do it. For reference for others:

![image](https://user-images.githubusercontent.com/10754765/87245949-0e042c80-c44a-11ea-9808-a6496dadb809.png)

In case you want a permanent solution, which would continue working after you updated to the next version of the module, try putting these lines into your PowerShell profile:

``` PowerShell
Import-Module oh-my-posh
$ThemeSettings.Options.ConsoleTitle = $false
# then you can set a theme
Set-Theme Paradox
```

The goal is to change the configuration before you set a theme, because you want to avoid  changing the value of `$host.ui.RawUI.WindowTitle`

After you set a theme, and the WindowTitle is updated by `oh-my-posh`, changing the configuration will not revert back the title, but you can change it at your will:
 ``` PowerShell
$host.ui.RawUI.WindowTitle = "PowerShell"
```

I hope this helps.

**Comment by FlorentLM** [comment]
Thanks for the explanation!
