### ISSUE TITLE
oh-my-posh causes iTerm2 (Mac) to show an alert with every prompt

### ISSUE THREAD

**Issue by damianpowell** [JanDeDobbeleer/oh-my-posh2#261]
Oh-my-posh seems to cause iTerm2 to show an alert with every prompt. I don't know what is causing this. I'll happy dig into this if you could give me a clue where to look?

<img alt="Prompt causes alert in iTerm2" src="https://3bbqpg.db.files.1drv.com/y4mg0mhBnaZ4RdJjm2pd7GNJSHkWqXliQyRhqSc7R5sBpZqFhJ3oxzyDOaSHy_NwhS-Ya8MZwD5qRkTA_xYwUQrPFcyHsLpKmEV2bt_GEg_syASahE2l1wk6r2GOJHJZRb-zN_puTvdtw4XvCmwoq6UGTyuP-27aPdggHA0_P0e_9O3iSnUrZNI7cTncZEA_7HE0_7uS4f9TVFtd928CXPbQQ?width=2520&height=1576&cropmode=none">

I'm using the same font (Cascadia Mono PL) in iTerm2 with oh-my-zsh and it seems to work fine so I guess oh-my-posh is outputting something that causes a BEL or some other code that iTerm2 is interpreting as an alert?

**Comment by damianpowell** [comment]
I've tried all of the themes and the problem occurs for all of them so it appears to be a problem that is global, not specific to a given theme.

**Comment by PinLin** [comment]
I have the same problem. I use SSH to connect to my Windows PC on iTerm2, then run Powershell and oh-my-posh.

**Comment by damianpowell** [comment]
This seems to be caused by the following addition to the prompt:

```PowerShell
if ($location.Provider.Name -eq "FileSystem") {
    $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
}
```

I'm not sure what the intention of this code is, but in iTerm2, the result is a message box containing "9; [value of pwd]" is displayed along with an irritating chime. My hacky fix for this is to modify `oh-my-posh.psm1` as shown below:

```PowerShell
if ($location.Provider.Name -eq "FileSystem" -and $env:LC_TERMINAL -ne 'iTerm2') {
    $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
}
```

**Comment by damianpowell** [comment]
BTW, @JanDeDobbeleer, in PowerShell, `"$([char]27)"` can be written as ``"`e"`` which might be a bit clearer.

**Comment by code-doge** [comment]
I have the same problem, @damianpowell , did you figure out any workaround for this issue? Thanks.

**Comment by code-doge** [comment]
I have to temporarily disable notification for Iterm2

**Comment by analogrelay** [comment]
Yep, seeing the same for me on iTerm2. The escape sequence `OSC 9` (i.e. <code>`e]9;some text</code>) on iTerm2 is documented as used to send a notification to the macOS notification center: https://iterm2.com/documentation-escape-codes.html

It looks like this is used by ConEmu to set the window title: https://conemu.github.io/en/AnsiEscapeCodes.html#ConEmu_specific_OSC 

Could we make this code specific to ConEmu somehow? I.e. something like @damianpowell 's suggestion that disables it for iTerm2, but flipped around so that it only enables it in ConEmu. These OSC codes (beyond what xterm defines) are a bit of a wild-west so focusing them on specific terminals seems best.

**Comment by analogrelay** [comment]
FYI, I fixed this without patching using code like this in my profile:

```pwsh
if($env:LC_TERMINAL -eq "iTerm2") {
    $ThemeSettings.Options.ConsoleTitle = $false
}
```
