### ISSUE TITLE
Theme (Suggestion)

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh2#298]
Would You Please consider checking out my repo I made a new [theme](https://github.com/v1nay90/oh-my-posh-custom-theme) and I guess it looks neat could you please consider adding my theme to the project

**Comment by JanDeDobbeleer** [comment]
I like this theme a lot, is it OK if I add it to the new engine rather than the current one? If all goes well, it's going to be config and not a custom script in that case ;-)

**Comment by ghost** [comment]
nice! That's awesome so when is the new engine coming out I'am excited

**Comment by JanDeDobbeleer** [comment]
I'm working on it ATM, just added a battery indicator function as that seems to be in your theme as well :-)

**Comment by ghost** [comment]
Ya that was inspierd from the powerlevel9k theme which apparently does not work in my laptop it some error which can be fixed it caused because the creator did not put the glyphs in a variable (utf-32) so its some powershell error, anyways i dragged the battery from there

**Comment by v1nay90** [comment]
`At C:\Users\vinay\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.468\Themes\Powerlevel9k.psm1:120 char:44
+ ... mpt += Write-Prompt -Object "â•šâ•" -ForegroundColor $indicatorColor
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: ".
At C:\Users\vinay\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.468\Themes\Powerlevel9k.psm1:3 char:22
+ function Write-Theme {
+                      ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

Import-Module : The specified module
'C:\Users\vinay\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.468\Themes\Powerlevel9k.psm1' was not loaded
because no valid module file was found in any module directory.
At C:\Users\vinay\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.468\oh-my-posh.psm1:12 char:5
+     Import-Module $sl.CurrentThemeLocation -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\vinay\...werlevel9k.psm1:String) [Import-Module], File
   NotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand`

**Comment by JanDeDobbeleer** [comment]
Hey @v1nay90  . I just published my [new engine](https://www.powershellgallery.com/packages/go-my-posh). That one has a first version of [your theme](https://github.com/JanDeDobbeleer/go-my-posh/blob/master/Themes/aliens.json) :-)

You can install and use it as follows

```powershell
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt aliens
```

if you want, you can also list all available themes

```powershell
Get-PoshThemes
```

Feel free to create an issue there as well to follow up in case you find problems with the theme or anything else.
I will keep an eye on `oh-my-posh`, but I'll favor `go-my-posh` going forward.

**Comment by ghost** [comment]
Thank you so much and congrats on sucessful launch of the new engine best of luck

**Comment by ghost** [comment]
i like what u have done to it its awesome and faster
