### ISSUE TITLE
Not getting expected colors of prompt symbols in Agnoster and some other themes

### ISSUE THREAD

**Issue by dimiboi** [JanDeDobbeleer/oh-my-posh2#43]
![oh-my-posh-agnoster](https://cloud.githubusercontent.com/assets/4341162/25274930/50ffcb3e-269b-11e7-978d-112d187f5a64.png)

**Comment by JanDeDobbeleer** [comment]
It's more of a conemu or ps issue (I think) than the module's. I know I can fix this when I set magenta as black also, and then use Magenta as the backgroundcolor.

**Comment by dimiboi** [comment]
Any idea what could be a workaround?

**Comment by JanDeDobbeleer** [comment]
I'll post one tomorrow (on mobile right now)

**Comment by JanDeDobbeleer** [comment]
I added these changes:

    $ThemeSettings.Colors.SessionInfoBackgroundColor = [ConsoleColor]::Magenta
    $ThemeSettings.Colors.GitForegroundColor = [ConsoleColor]::Magenta

This implies that color number 13 (Magenta) gets the same color as 0 (Black)

**Comment by ayrtonmassey** [comment]
This an issue with `posh-git`. It has been fixed (see https://github.com/dahlbyk/posh-git/pull/454) but the fix has not been published to the PowerShell Gallery (see https://github.com/dahlbyk/posh-git/issues/470)

The `Write-Prompt` function was checking whether its `-ForegroundColor` parameter was empty using the condition `!ForegroundColor`. If you pass it `[ConsoleColor]::Black`, that condition becomes `!0` which is obviously `True` and thus the default color is used instead of `Black`.

**Comment by JGJP** [comment]
Sorry for commenting on an old issue and for a dumb question but how do I make these changes persist after closing ConEmu?

```
$ThemeSettings.Colors.SessionInfoBackgroundColor = [ConsoleColor]::Magenta
$ThemeSettings.Colors.GitForegroundColor = [ConsoleColor]::Magenta
```

edit: these 2 lines go into the Powershell profile. Type `ise $PROFILE` and add them at the end of the file. Amend ConEmu color scheme by changing color 13 (Magenta) to match 1 (Black)

**Comment by JanDeDobbeleer** [comment]
I'll close this as the fix from posh-git is nearing release.
