### ISSUE TITLE
Icons for different themes do not appear on newline

### ISSUE THREAD

**Issue by bastijnv** [JanDeDobbeleer/oh-my-posh2#82]
In themes that span multiple lines the symbols added after Set-Newline are added to the first line instead (at the end). E.g. Honukai from repository does:
```
# USER at MACHINE in ~ [16:54:44] ⚡ ➜
```
instead of:
```
# USER at MACHINE in ~ [16:54:44] 
⚡ ➜
```

This could be easily resolved by replacing:
```
$prompt += Set-Newline 
```
With 
```
$prompt += Write-Prompt "`n"
```
in the theme scripts.

**Comment by fenneh** [comment]
Have noticed the exact same behaviour when using the Hyper terminal. 

Including PS version and OS version, not sure if this is a problem caused by an OS update. 

```
# fen at HOME in C:\dev [20:57:56]
➜  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

# fen at HOME in C:\dev [20:59:11]
➜  [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0
```

Relevant doc I can find regarding the esc sequence being used

* https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idtextformattingspanspan-idtextformattingspanspan-idtextformattingspantext-formatting

**Comment by JanDeDobbeleer** [comment]
It's backlog item, I can alter the Set-Newline function which uses an ANSI escape sequence to set a newline, but for some reason not all terminals understand this.
